### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by tobiasmcnulty** [pjobson/openwrt-dell-wyze-3040#1]
Thanks for putting this guide together! I was having trouble getting OpenWRT to boot on my Wyse 3040 until I found your note about disabling the serial console. In case it's helpful, I found it's also possible to alter the kernel command line in `grub.cfg` in pre-built images (whether official or built via the Image Builder), so you don't need to build a full custom image if you don't want to: https://github.com/tobiasmcnulty/router-openwrt/blob/main/generate-no-serial-images.sh

For a ready-built image that works on the Wyse 3040, you'll want the `-squashfs-combined-efi-no-serial` variant from the [latest release](https://github.com/tobiasmcnulty/router-openwrt/releases).

<img width="966" alt="Screen Shot 2022-07-10 at 8 32 58 PM" src="https://user-images.githubusercontent.com/160132/178168754-fbf7e4fa-b01b-4822-9656-2bcb3be31c88.png">

**Comment by pjobson** [comment]
Happy to help!
