### ISSUE TITLE
Performance degraded when no monitor attached

### ISSUE THREAD

**Issue by bill888uk** [pjobson/openwrt-dell-wyze-3040#2]
fwiw, I used menuconfig to compile my own test images based on your instructions to test from USB flash drive.

https://forum.openwrt.org/t/dell-wyse-3040-and-openvpn/181578

I also managed to use the standard images from Openwrt Firmware Selector and post editing the grub.cfg, to get the image to boot from USB flash drive, after advice from OpenWrt forum.

I don't know if you came across this issue, but I observed when testing openvpn speeds, my device speed is degraded if no monitor is connected to the Display Port at the time Openwrt boots up.  

eg. openvpn speeds dropped from 135 mbps to 40 mbps.  The cores barely rise above 480 MHz.

I've ordered a dummy plug to insert into one of the Display Port sockets to overcome the need to have a monitor permanently connected to the 3040.   Hopefully this will restore full performance.

The BIOS version on my 3040 is v1.2.5.  I think that is the latest version available.

**Comment by pjobson** [comment]
@bill888uk  did you have any luck with your dummy plug?

**Comment by bill888uk** [comment]
I tested a HDMI dummy plug with two DP to HDMI adapter leads.  One existing lead worked, the other newly purchased lead was not compatible (but worked fine in PC) .   The Display Port dummy plug worked.  No degradation in performance observed in past 6+ weeks with the DP dummy plug purchased from eBay China seller.

**Comment by pjobson** [comment]
Thanks for the follow up!!

**Comment by pjobson** [comment]
According to this, the 23.05.3 image works out of the box, you may want to try that one.

https://github.com/pjobson/dell-wyse-3040-openwrt/issues/3
