### ISSUE TITLE
This guide is in big parts obsolete

### ISSUE THREAD

**Issue by boerni667** [pjobson/openwrt-dell-wyze-3040#3]
OpenWRT 23.05.3 (openwrt-23.05.3-x86-64-generic-ext4-combined-efi.img.gz) runs fine on the wyse, it's just needed to delete all the Serial options in the Linux Cmdline in /boot/grub/grub.cfg after the kernel entry

By using the official image and not a self compiled image, you won't run into this issue i had lately because i was running a self-compiled-build: https://openwrt.org/faq/cannot_satisfy_dependencies

Other side notes:

I've added a Realtek R8152 USB3 2.5GB NIC, it runs fine on the front port.

A Displayport Dummy Dongle does work fine to "unlock" the cpu, but also ive added following in /etc/rc.local

echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo performance > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
echo performance > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
echo performance > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor

(ash didnt like my bash style for loop, so unroll loops ftw)

This way the CPU always works in full throttle and it routes without problems my 1Gbit/s Fiber Connection. I didn't see a big difference in power consumption at all. With Ondemand or Schedutil it could only reach 700mbit/s. Wireguard can also saturate the 1gbit/s line without problems on this machine

Main Reason i've went for the wyse is the size. My enclosure in my flat where the fiber comes out and the ethernet connections to the rooms are is e.g. too small for a Futro S920, which ive used before. but big enough for the wyse and a small managed 5 port switch

**Comment by pjobson** [comment]
Thanks for the feedback.  I'm glad that 23.05.3 runs well on the unit.  I'll close this and put it at the top of the README.
